import { Todo } from "./types";

export const DEMO_TODOS: Todo[] = [
  {
    id: "1",
    title: "Finish project proposal",
    description: "Write the Q2 proposal and send to manager",
    completed: false,
    priority: "high",
    category: "work",
    createdAt: new Date("2026-03-20"),
    dueDate: new Date("2026-03-28"),
  },
  {
    id: "2",
    title: "Buy groceries",
    description: "Milk, eggs, bread, and vegetables",
    completed: true,
    priority: "medium",
    category: "shopping",
    createdAt: new Date("2026-03-22"),
    dueDate: new Date("2026-03-23"),
  },
  {
    id: "3",
    title: "Morning workout",
    description: "30 minute run and stretching",
    completed: false,
    priority: "medium",
    category: "health",
    createdAt: new Date("2026-03-25"),
    dueDate: new Date("2026-03-26"),
  },
  {
    id: "4",
    title: "Call dentist",
    description: "Schedule annual checkup",
    completed: false,
    priority: "low",
    category: "health",
    createdAt: new Date("2026-03-24"),
    dueDate: new Date("2026-03-31"),
  },
  {
    id: "5",
    title: "Review pull request",
    description: "Review the authentication refactor PR",
    completed: true,
    priority: "high",
    category: "work",
    createdAt: new Date("2026-03-21"),
    dueDate: new Date("2026-03-22"),
  },
  {
    id: "6",
    title: "Plan birthday party",
    description: "Organize venue and invite guests",
    completed: false,
    priority: "low",
    category: "personal",
    createdAt: new Date("2026-03-25"),
    dueDate: new Date("2026-04-05"),
  },
  {
    id: "7",
    title: "Update resume",
    completed: false,
    priority: "medium",
    category: "personal",
    createdAt: new Date("2026-03-23"),
    dueDate: new Date("2026-03-30"),
  },
  {
    id: "8",
    title: "Team meeting prep",
    description: "Prepare slides for the weekly sync",
    completed: true,
    priority: "high",
    category: "work",
    createdAt: new Date("2026-03-25"),
    dueDate: new Date("2026-03-26"),
  },
];
