import { Todo } from "./types";

export const DEMO_TODOS: Todo[] = [
  {
    id: "1",
    title: "Review Q1 project proposal",
    description: "Go through the proposal and leave comments before the team meeting.",
    completed: false,
    priority: "high",
    category: "work",
    createdAt: new Date("2026-03-20"),
    dueDate: new Date("2026-03-27"),
  },
  {
    id: "2",
    title: "Buy groceries",
    description: "Milk, eggs, bread, avocados, and coffee.",
    completed: false,
    priority: "medium",
    category: "shopping",
    createdAt: new Date("2026-03-24"),
    dueDate: new Date("2026-03-26"),
  },
  {
    id: "3",
    title: "Morning run",
    description: "5 km run at the park.",
    completed: true,
    priority: "medium",
    category: "health",
    createdAt: new Date("2026-03-25"),
  },
  {
    id: "4",
    title: "Fix login bug",
    description: "Users report being logged out after 10 minutes. Investigate session expiry logic.",
    completed: false,
    priority: "high",
    category: "work",
    createdAt: new Date("2026-03-22"),
    dueDate: new Date("2026-03-28"),
  },
  {
    id: "5",
    title: "Call dentist",
    description: "Schedule a cleaning appointment.",
    completed: false,
    priority: "low",
    category: "health",
    createdAt: new Date("2026-03-23"),
  },
  {
    id: "6",
    title: "Read 'The Pragmatic Programmer'",
    description: "Finish chapters 4 and 5.",
    completed: true,
    priority: "low",
    category: "personal",
    createdAt: new Date("2026-03-18"),
  },
  {
    id: "7",
    title: "Prepare sprint retrospective",
    description: "Gather metrics and draft talking points for Friday's retro.",
    completed: false,
    priority: "medium",
    category: "work",
    createdAt: new Date("2026-03-25"),
    dueDate: new Date("2026-03-28"),
  },
  {
    id: "8",
    title: "Order birthday gift for mom",
    description: "Check wishlist and order with express shipping.",
    completed: false,
    priority: "high",
    category: "shopping",
    createdAt: new Date("2026-03-24"),
    dueDate: new Date("2026-03-30"),
  },
];
